### ISSUE TITLE
what meaning of X in Algorithm 2?

### ISSUE THREAD

**Issue by zhaowumian7** [UCSC-VLAA/MicroDiffusion#3]
Hi, this is a great work, but I have a question. we know that we need condition information which contains Eimg and Epos, so Eimg needs 2D projections information. In fact, we only know a little of 2D projections, So there are a question that we should know all 2D projections to execute Algorithm 2 sampling function of Microdiffusion. Looking forward to your answer！

**Comment by TheFllood** [comment]
In our model we do linear interpolation of six neighboring 2D projections as $\mathbf{X}$. Providing all 2D projections could be a good approach, but this introduces additional computational overhead and may require more data for training.
