### ISSUE TITLE
Question about the input for diffusion module

### ISSUE THREAD

**Issue by Huang-XN** [UCSC-VLAA/MicroDiffusion#4]
Hi there,
Thank you for your excellent work. I am a very beginner to this area.

I have a question about the workflow. When the INR finished training session, it would output a rendered object and weight for the network. Afterwards, diffusion module started running. But I have no idea of what data should be taken as input for diffusion module. 

Hope you could answer it. 
Thanks a lot

Huang

**Comment by TheFllood** [comment]
Hi, the diffusion model takes the "2D Projections", "3D Coordinate" and "the output of the INR at the 3D Coordinate" as the input.
