### ISSUE TITLE
About eve.py

### ISSUE THREAD

**Issue by pluto0528** [UCSC-VLAA/MicroDiffusion#5]
hello,In the order in README, I trained the INR using neurous_inr.npy to get the weight of the INR model, neurous.pth. Then, I trained the diffusion model using the heavy file neurous.pth and the data set neurous.npy. And get the_lastepoch.pt. Finally, when running eve.py, I set path_to_inr_result to neurous_inr.npy, path_to_gt_result to neurous.npy, and path to generate result to sample generated images. After these parameters are set and run, the problem of data dimension mismatch occurs
![image](https://github.com/user-attachments/assets/077d5997-d2d5-4c8c-aecd-62600a95f9da)
![image](https://github.com/user-attachments/assets/e33b5766-aabc-43c2-bc51-ae6fd81085f8)
![image](https://github.com/user-attachments/assets/72deabc2-b697-4efe-aaf2-4be10c3c35a1)
If there is a problem with the parameters I set, or if there is a problem with my training process, I would be grateful if you would like to reply to me

**Comment by akexxxx-xk** [comment]
Have you solved this problem yet?
